# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 23:48
from __future__ import unicode_literals

import common.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('common', '0011_auto_20180429_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
                ('maximum_size', models.PositiveIntegerField(verbose_name='Maximum size')),
                ('object_id', models.PositiveIntegerField()),
                ('storage_instance_path', models.CharField(max_length=255, verbose_name='Storage instance path')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Cache',
                'verbose_name_plural': 'Caches',
            },
        ),
        migrations.CreateModel(
            name='CacheFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date time')),
                ('filename', models.CharField(max_length=128, verbose_name='Filename')),
                ('file_size', models.PositiveIntegerField(db_index=True, default=0, verbose_name='File size')),
                ('cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='common.Cache', verbose_name='Cache')),
            ],
            options={
                'get_latest_by': 'datetime',
                'verbose_name': 'Cache file',
                'verbose_name_plural': 'Cache files',
            },
        ),
        migrations.AlterField(
            model_name='shareduploadedfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/usr/local/development/mayan-edms/mayan/media/shared_files'), upload_to=common.models.upload_to, verbose_name='File'),
        ),
    ]
